[tool.black]
line-length = 120
target-version = ["py38"]

[tool.isort]
profile = "black"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
strict = true
